[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name="camel"
version="0.0.1"
authors=[
    {name="CAMEL TEAM", email="camel.ai.team@gmail.com"},
]
description="Communicative Agents for AI Society Study"
readme="README.md"
requires-python=">=3.7"
keywords=[
    "communicative-ai",
    "ai-societies",
    "artificial-intelligence",
    "deep-learning",
    "multi-agent-systems",
    "cooperative-ai",
    "natural-language-processing",
    "large-language-models",
]
classifiers=[
    "Development Status :: 2 - Pre-Alpha",
    "License :: OSI Approved :: Apache License 2.0",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3 :: Only",
]

dynamic=["dependencies", "optional-dependencies"]

[project.urls]
homepage="https://www.camel-ai.org/"
repository="https://github.com/lightaime/camel"
changelog="https://github.com/lightaime/camel/blob/master/CHANGELOG.md"

[tool.yapf]
based_on_style = "pep8"
split_before_named_assigns = false

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
skip = [".gitingore", "__init__.py"]

[tool.pytest.ini_options]
pythonpath = [
    ".",
]
