version: "3.9"
services:
  camel:
    image: camel:py3.10
    container_name: camel
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env
    command: ["python", "ai_society/role_playing.py"]
