name: Pre Commit Check

on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

jobs:
    pre-commit:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python environment and install dependencies
        uses: ./.github/actions/camel_install
        with:
          python-version: "3.8"
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files
