name: Publish Docker Image

on:
  release:
    types: [ published ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PACKAGE_PAT }}

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/camel-ai/camel:${{ github.ref_name }} \
            --sbom=false --provenance=false \
            --file .container/minimal_build/Dockerfile \
            --push .
